### ISSUE TITLE
"listen directive can only be attached directly to an element." should tell me which file.

### ISSUE THREAD

**Issue by jalenmmorgan** [electrovir/element-vir#17]
Here's an example of an error.

```reactive-element.ts:1233 Uncaught (in promise) Error: listen directive can only be attached directly to an element.
    at assertIsElementPartInfo (directive-helpers.js:9:15)
    at extractElement (directive-helpers.js:3:5)
    at new <anonymous> (listen.directive.js:14:24)
    at resolveDirective (lit-html.ts:1067:26)
    at ChildPart._$setValue (lit-html.ts:1357:13)
    at TemplateInstance._update (lit-html.ts:1187:16)
    at ChildPart._commitTemplateResult (lit-html.ts:1545:16)
    at ChildPart._$setValue (lit-html.ts:1379:12)
    at render (lit-html.ts:2175:8)
    at _a2.update (lit-element.ts:165:24)
```
    
  I'm not sure which file this error is in. Can error messaging be improved to include the file path?

**Comment by electrovir** [comment]
Good point. I'm not sure we can really modify the stack trace itself because `lit` is what's running these directives. Looks like we can at least grab the host element's tag name from within the directive to print an error like this instead:

> listen directive can only be attached directly to an element: found in element-vir-test-app

**Comment by jalenmmorgan** [comment]
If you're curious about the specific code that caused this, I had an extra `>`.

```
const createNewHabitScreen = html`
            <${CreateNewHabitScreen}>
                ${listen(CreateNewHabitScreen.events.navigateToScreen, (event) => {
                    updateState({currentAppScreen: event.detail});
                })}>
            </${CreateNewHabitScreen}>
```
